[package]
name = "fibonacci"
version = "0.1.0"
authors = ["abdo643 <abou.shehata643@yahoo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
